name: Compile interpreter

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install NASM
        run: sudo apt-get update && sudo apt-get install -y nasm
      - name: Make bash script executable
        run: chmod +x ./compile.sh
      - name: Run bash script
        run: ./compile.sh
